name: publish
on:
  - push
  - create
jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      # image tag
      - name: set image tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          REF_TYPE=${GITHUB_REF%/*}

          if [[ "REF_TYPE" == "ref/tags" ]]; then
            echo ::set-output name=tag::${TAG_NAME:1}
          else
            if [[ "$TAG_NAME" == "master" ]]; then
              echo ::set-output name=tag::latest
            else
              TAG_NAME=${TAG_NAME////-}
              echo ::set-output name=tag::${TAG_NAME}-${GITHUB_SHA::8}
            fi
          fi
        id: image

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build/Publish
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: mischal/releasing-test/hello-world2
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          tags: ${{ steps.image.outputs.tag }}