name: publish
on:
  - push
  - create
jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: jerray/publish-docker-action@v1.0.0
        with:
          registry: docker.pkg.github.com
          repository: mischal/releasing-test/hello-world
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auto_tag: true